class SettlementGenerator {
  constructor() {
    this.settlementRules = [
      { type: 'Single Dwelling', range: [1, 3], population: [1, 12] },
      { type: 'Thorp', range: [4, 5], population: [20, 80] },
      { type: 'Hamlet', range: [6, 7], population: [100, 400] },
      { type: 'Village', range: [8, 9], population: [600, 900] },
      { type: 'Town', range: [10, 10], population: [1500, 6500] },
      { type: 'City', range: [11, 11], population: [10000, 60000] },
      { type: 'Castle', range: [12, 14] },
      { type: 'Ruins', range: [15, 16] },
      { type: 'Uninhabited', range: [17, 100] }
    ]
    this.reRollRules = [
      { type: 'Ruined Village', range: [1, 30] },
      { type: 'Ruined City', range: [31, 60] },
      { type: 'Ruined Shrine', range: [61, 85] },
      { type: 'Ruined Tomb', range: [86, 100] }
    ]
    this.castleSizeRules = [
      { size: 'Small', range: [1, 10], type: 'Small shell keep' },
      { size: 'Small', range: [11, 25], type: 'Tower' },
      { size: 'Small', range: [26, 35], type: 'Moat house or friary' },
      { size: 'Medium', range: [36, 45], type: 'Large shell keep' },
      { size: 'Medium', range: [46, 65], type: 'Small walled castle with keep' },
      { size: 'Medium', range: [66, 80], type: 'Medium walled castle with keep' },
      { size: 'Large', range: [81, 88], type: 'Concentric castle' },
      { size: 'Large', range: [89, 95], type: 'Large walled castle with keep' },
      { size: 'Large', range: [96, 100], type: 'Fortress complex' }
    ]
    this.castleInhabitantsRules = {
      'Small': [
        { type: 'Totally deserted', range: [1, 45] },
        { type: 'Deserted (monster therein)', range: [46, 60] },
        { type: 'Humans', range: [61, 70] },
        { type: 'Character-types', range: [71, 100] }
      ],
      'Medium': [
        { type: 'Totally deserted', range: [1, 30] },
        { type: 'Deserted (monster therein)', range: [31, 50] },
        { type: 'Humans', range: [51, 65] },
        { type: 'Character-types', range: [66, 100] }
      ],
      'Large': [
        { type: 'Totally deserted', range: [1, 15] },
        { type: 'Deserted (monster therein)', range: [16, 40] },
        { type: 'Humans', range: [41, 60] },
        { type: 'Character-types', range: [61, 100] }
      ]
    }
  }

  getHumans() {
    const roll = Math.floor(Math.random() * 100) + 1
    if (roll <= 25) return 'Bandits'
    if (roll <= 85) return 'Brigands'
    if (roll <= 97) return 'Berserkers'
    return 'Dervishes'
  }

  getCharacterTypes() {
    const roll = Math.floor(Math.random() * 100) + 1
    if (roll <= 18) return { type: 'Cleric', level: this.randomInRange([9, 12]) }
    if (roll <= 20) return { type: 'Druid', level: this.randomInRange([12, 13]) }
    if (roll <= 65) return { type: 'Fighter', level: this.randomInRange([9, 12]) }
    if (roll <= 66) return { type: 'Paladin', level: this.randomInRange([9, 10]) }
    if (roll <= 68) return { type: 'Ranger', level: this.randomInRange([10, 13]) }
    if (roll <= 80) return { type: 'Magic-User', level: this.randomInRange([11, 13]) }
    if (roll <= 85) return { type: 'Illusionist', level: this.randomInRange([10, 13]) }
    if (roll <= 93) return { type: 'Thief', level: this.randomInRange([10, 14]) }
    if (roll <= 96) return { type: 'Assassin', level: 14 }
    if (roll <= 99) return { type: 'Monk', level: this.randomInRange([9, 12]) }
    return { type: 'Bard', level: 23 }
  }

  getSettlementType(roll) {
    for (const rule of this.settlementRules) {
      if (roll >= rule.range[0] && roll <= rule.range[1]) {
        if (rule.type === 'Ruins') {
          return { type: this.getReRolledSettlementType(), population: 0 }
        } else if (rule.type === 'Castle') {
          return { type: this.getCastleDetails(), population: 0 }
        }
        const population = rule.population ? this.randomInRange(rule.population) : 0
        return { type: rule.type, population }
      }
    }
    return { type: 'Uninhabited', population: 0 }
  }

  getReRolledSettlementType() {
    const reRoll = Math.floor(Math.random() * 100) + 1
    for (const rule of this.reRollRules) {
      if (reRoll >= rule.range[0] && reRoll <= rule.range[1]) {
        return rule.type
      }
    }
    return 'Uninhabited'
  }

  getCastleDetails() {
    const castleRoll = Math.floor(Math.random() * 100) + 1
    let castleSize = 'Unknown'
    let castleType = 'Unknown'
    
    for (const rule of this.castleSizeRules) {
      if (castleRoll >= rule.range[0] && castleRoll <= rule.range[1]) {
        castleSize = rule.size
        castleType = rule.type
        break
      }
    }

    const inhabitantRoll = Math.floor(Math.random() * 100) + 1
    let inhabitants = 'Unknown'
    
    for (const rule of this.castleInhabitantsRules[castleSize]) {
      if (inhabitantRoll >= rule.range[0] && inhabitantRoll <= rule.range[1]) {
        inhabitants = rule.type
        break
      }
    }

    if (inhabitants === 'Humans') {
      inhabitants = this.getHumans()
    } else if (inhabitants === 'Character-types') {
      inhabitants = this.getCharacterTypes()
    }

    return `Castle (${castleType}, ${inhabitants.type ? inhabitants.type : inhabitants}, Level: ${inhabitants.level ? inhabitants.level : 'N/A'})`
  }

  randomInRange(range) {
    const [min, max] = range
    return Math.floor(Math.random() * (max - min + 1)) + min
  }
}

const village = [
	"Ufora",
	"Hogsfeet",
	"Tamworth",
	"Tywardreath",
	"Butterpond",
	"Padstow",
	"Bradfordshire",
	"Bexley",
	"Hillford",
	"Calcheth",
	"Murkwell",
	"Anghor Wat",
	"Monmouth",
	"Cherrytown",
	"Banrockburn",
	"Haling Cove",
	"Carningsby",
	"Penkurth",
	"Wanborne",
	"Favorsham",
	"Zalfari",
	"Coombe",
	"Scrabster",
	"Penketh",
	"Crossroads",
	"Auchendinny",
	"Macclesfield",
	"Porthcawl",
	"South Warren",
	"Daemarrel",
	"Tottenham",
	"Oldham",
	"Pathstow",
	"Aria",
	"Barnsley",
	"Boroughton",
	"Beggar's Hole",
	"Moonbright",
	"Bleakburn",
	"Hankala",
	"Auchendale",
	"Penzance",
	"Norton",
	"Sanlow",
	"Lunaris",
	"Dewsbury",
	"Narnclaedra",
	"Harthwaite",
	"Watford",
	"Tregaron",
	"Waeldestone",
	"Red Hawk",
	"Snowbush",
	"Ilragorn",
	"Newsham",
	"Tunstead",
	"Myrrka",
	"Bannockburn",
	"Crullfeld",
	"Helmfirth",
	"Langdale",
	"Ashborne",
	"Bailymena",
	"Stathmore",
	"Clacton",
	"Wavemeet",
	"Nishka",
	"Pella's Wish",
	"Holsworthy",
	"Larnwick",
	"Cardended",
	"Acrine",
	"Islesbury",
	"Sharnwick",
	"Durnatel",
	"Blackpool",
	"Hollyhead",
	"Ampleforth",
	"Wolford",
	"Faversham",
	"Axminster",
	"Larkinge",
	"Yarrin",
	"Skystead",
	"Nantgarth",
	"Zeffari",
	"Sudbury",
	"Westray",
	"Drumnacanvy",
	"Calmarnock",
	"Newham",
	"Grasmere",
	"Fanfoss",
	"Oar's Rest",
	"Beachcastle",
	"Bradford",
	"Fortaare",
	"Sheffield",
	"Lingmell",
	"Fool's March",
	"Pontybridge",
	"Kilmarnock",
	"Perthlochry",
	"Hirane",
	"Bullmar",
	"Colchester",
	"Kilerth",
	"Mensfield",
	"Fernsworth",
	"Crasmere",
	"Arkala",
	"Haerndean",
	"Glaenarm",
	"Wealdstone",
	"Wolfden",
	"Aroonshire",
	"Calchester",
	"Violl's Garden",
	"Moressley",
	"Poltragow",
	"Blencathra",
	"Caelfall",
	"Beckinsdale",
	"Willsden",
	"Caister",
	"Peterborough",
	"Marren's Eve",
	"Veritas",
	"Kinecardine",
	"Orilon",
	"Katinhanta",
	"Draycott",
	"Cullfield",
	"Longdale",
	"Fallholt",
	"Galssop",
	"Sutton",
	"Mestauskalio",
	"Glanchester",
	"Garthram",
	"Northon",
	"Peatsland",
	"Haran",
	"Cromer",
	"Firebend",
	"Nerton",
	"Llaneybyder",
	"Hampstead",
	"Grimsby",
	"Caerleon",
	"Bredon",
	"Farnworth",
	"Archmouth",
	"Lancaster",
	"Azmarin",
	"Hardersfield",
	"Wallowdale",
	"Lakeshore",
	"Solari",
	"Goldenleaf",
	"Pernrith",
	"Lerwick",
	"Seameet",
	"Rochdale",
	"Black Crystal",
	"Alcombey",
	"Huthwaite",
	"Arkaley",
	"Woodpine",
	"Ruthorham",
	"Pirn",
	"Perlshaw",
	"Bamburgh",
	"Astrakane",
	"Mansfield",
	"Coniston",
	"Black Hallows",
	"Jedburgh",
	"Tow",
	"Holden",
	"Waekefield",
	"Whiteridge",
	"Pitmerden",
	"Cumdivock",
	"Bournemouth",
	"Arcton",
	"Holbeck",
	"Cirrane",
	"Murtovaara",
	"Blencalgo",
	"Dornwich",
	"Halivaara",
	"Millstone",
	"Doncaster",
	"Acton",
	"Bromwich",
	"Kameeraska",
	"Gramsby",
	"Lhanbyrde",
	"Alderham",
	"Wealdlock",
	"Strathkeld",
	"Oldaton",
	"Mynyddburn",
	"Hogring",
	"Awkalea",
	"Fleshampton",
	"Lawsby",
	"Dripsnake",
	"Venaldame",
	"Vileshagg Lake",
	"Slavechute Hill",
	"Stinkbane",
	"Morttor",
	"Exebeck",
	"Woldmore",
	"Blazemount",
	"Denburgh",
	"Bitehovel Marsh",
	"Fatmede",
	"Killmancatt",
	"Langton",
	"Hawkoflea",
	"Devilach",
	"Monkfall",
	"Whelchester",
	"Leser Mynyddmere",
	"Painlea",
	"Fatleigh",
	"Monkbeat",
	"Marenden",
	"Holmside",
	"Aldermere Lake",
	"Spidersoflea",
	"Pontingham",
	"Foglowe",
	"Slavebugga",
	"Mount Dogoch",
	"Horefall Lake",
	"Leser Dinasmouth",
	"Redpool Fell",
	"Paintower",
	"Pitenden",
	"Horettin Mount",
	"Blackshen",
	"Llyndean",
	"Inverbryde Lake",
	"Treton",
	"Piratebugr Temple",
	"Worldsing",
	"Balingford",
	"Rendtease",
	"Stowtown",
	"Brigenhill Lodge",
	"Mormena",
	"Lyngburn",
	"Wesham",
	"Windleigh",
	"Illring",
	"Estorden",
	"Slaughterbunge",
	"Impsgrip",
	"Impsmede",
	"Breington",
	"Winterend",
	"Monkslot",
	"Belyslock",
	"Witchettin",
	"Holmster",
	"Spitmarshe",
	"Winterbridge",
	"Spothenge",
	"Angenford",
	"Hawkdroop",
	"Fisherscrutch",
	"Vilecastle",
	"Morworthy Castle",
	"Lanberry",
	"Bleddep",
	"Grimach",
	"Norlock",
	"Balasay",
	"Slimeington",
	"Itchyerscrutch Hills",
	"Hellsonas Lake",
	"Axeington",
	"Drumwardine",
	"Norsay",
	"Pucettin",
	"Moistely",
	"Somerchulish",
	"Norcheth",
	"Guiltyhalt",
	"Dorthwaite",
	"Shitester",
	"Lower Pipemount",
	"Norsby",
	"Shitettin",
	"Lickdame",
	"Knightance",
	"Worldsbeck",
	"Kineter",
	"Slutsmound",
	"Cunhole",
	"Lawwardine",
	"Skullslip Bridge",
	"Ashingford",
	"Killmanbugr",
	"Kilsey",
	"Lickoflea Bridge",
	"Helgame",
	"Filthtupp Farm",
	"Flopbunge",
	"Drunkoflea",
	"Whelsworth",
	"Moringham",
	"Huntingbran",
	"Mount Lhanetton",
	"Spidersgrip",
	"Smellhenge",
	"Fishwood",
	"Glamyscott",
	"Nankeld",
	"Dimmarshe",
	"Hawkerscrutch",
	"Exeingford",
	"Mordock",
	"Stickigrip",
	"Spidersbottom",
	"Morfeld",
	"Frozendame",
	"Dorham",
	"Astster",
	"Meatettin",
	"Boodysfolly",
	"Lickoflea Hill",
	"Morarder",
	"Houndskne Mountain",
	"Swinenden",
	"Culfield",
	"Pantingdene",
	"Trend",
	"Hurtdich Tor",
	"Drunkles",
	"East Huntingburn",
	"Someringdon",
	"Holmsey",
	"Knighttreath Mountain",
	"Strathbury Caves",
	"Puckdive",
	"Palmenden",
	"Belyscester",
	"Namysadale Moors",
	"Sadchute",
	"Llynsham",
	"Bourneshaw",
	"Morwich",
	"Port Balshen",
	"Evilbunge",
	"Blackenhill",
	"Lickonas",
	"Glamysworthy",
	"Puckander",
	"Deathtick",
	"Mortmede Bridge",
	"Killmantower Mount",
	"Aldstow",
	"Finham Hill",
	"Groklump",
	"Woldminster",
	"Minastow",
	"East Glamysanger",
	"Exelock",
	"Lower Sutmena",
	"Llynworthy",
	"Macden",
	"Illrise",
	"Ringgill",
	"Belysbeck",
	"Horebeat Down",
	"Dinasend Hill",
	"Drippinwind Mount",
	"Shepburgh",
	"Moistmarke Mountain",
	"Slavefall",
	"Fulstow",
	"Polminster",
	"Culbury",
	"Lickdive",
	"Blazedump",
	"Drumdale",
	"Hogkis",
	"Blazetick",
	"Angenden",
	"Billlowe",
	"Culington",
	"Axesham Down",
	"Itchyring",
	"Trenden Marsh",
	"Firerise",
	"Eldich",
	"Modesingham",
	"Brigtun",
	"Wormsgrip",
	"Venallea",
	"Worldston Lodge",
	"Blindbatte",
	"Venalslip",
	"Grentun",
	"Spitbugr",
	"Grokbreath Marsh",
	"Fireclapp",
	"Dalwich",
	"Monkcatt",
	"Dalster Moors",
	"Shafteadale",
	"Lickhalt",
	"Balashaw",
	"Asclapp Bridge",
	"Drunktor Lake",
	"Skullsllyn",
	"Dimllyn",
	"Axend",
	"Puckhalt",
	"Kilside",
	"Vilemound",
	"Belfos",
	"Stormely",
	"Taxylis Lake",
	"Guiltycrack",
	"Dengate Fell",
	"Bellock",
	"Namysaton",
	"Aslea",
	"Itchyaxe",
	"Holmshen",
	"Minasbran",
	"Auchtersey",
	"Inverdock",
	"Deathold Mount",
	"Askis Lodge",
	"Fulgill",
	"Fleshach",
	"Belmer",
	"Somerburgh",
	"Viledame",
	"Nastimarshe",
	"Estham",
	"Modesacombe Farm",
	"Lowampton Plains",
	"Lickhalt Plains",
	"Seaonas Farm",
	"Grotarmpit",
	"Wrongbent",
	"Illkne",
	"Belasington",
	"Olddean Hill",
	"Blackedene",
	"Hoppbumton Lake",
	"Minasfeld",
	"Fishbane",
	"Filthknock",
	"Langingdene",
	"Poisonknot",
	"Polbrough",
	"Nastidep Down",
	"Huntingthwaite",
	"Killock Mountain",
	"Witchdump Tor",
	"Sadles",
	"Poldean",
	"Enderlock",
	"Mortbane Barrow",
	"Gobblebane",
	"Hairdump",
	"Itchyonas Mount",
	"Gobbleslip",
	"Spotbugga",
	"Bledmarke Tor",
	"Filthrise",
	"Wealdstow",
	"Ponybottom",
	"Blindarmpit",
	"Mynyddchulish",
	"Firemes",
	"Gutkis",
	"Fishcave",
	"Brigbury",
	"Neatburgh",
	"Morchulish Castle",
	"Gobblesfolly Mountain",
	"South Macington",
	"Lyngster",
	"Mortbottom",
	"Panteter",
	"Gobbledame",
	"South Drippindump",
	"Leverbury Down",
	"Kilminstry",
	"Corley",
	"Mageshore",
	"Strongcourt",
	"Wildeburn",
	"Ashedge",
	"Rockshore",
	"Griffinmarsh",
	"Marshshore",
	"Springview",
	"Bushbridge",
	"Edgeham",
	"Falconmoor",
	"Westbarrow",
	"Greenby",
	"Lightash",
	"Springmeadow",
	"Freymead",
	"Highsnow",
	"Moorborough",
	"Iceland",
	"Violetfalcon",
	"Lightgrass",
	"Aelbank",
	"Dragonmill",
	"Newoak",
	"Vertmerrow",
	"Brookwyn",
	"Wellston",
	"Rockhollow",
	"Oldedge",
	"Strongston",
	"Vertness",
	"Clearmarsh",
	"Bysilver",
	"Bushmeadow",
	"Freylake",
	"Vertshade",
	"Shadowburn",
	"Mallowmead",
	"Eastmeadow",
	"Jangate",
	"Fallmont",
	"Highhurst",
	"Linfield",
	"Butterwind",
	"Beledge",
	"Summercoast",
	"Waterhedge",
	"Redmead",
	"Springhedge",
	"Wyvernston",
	"Elfbridge",
	"Bellmarsh",
	"Janwynne",
	"Northglass",
	"Wildecliff",
	"Byhill",
	"Wayfort",
	"Newwald",
	"Bellview",
	"Crystalbush",
	"Butterley",
	"Fallgate",
	"Lochston",
	"Valview",
	"Goldston",
	"Summernesse",
	"Southfield",
	"Janvale",
	"Greenmist",
	"Snowway",
	"Westgrass",
	"Westerhill",
	"Flowerbush",
	"Redwheat",
	"Olddell",
	"Glasshill",
	"Wildelyn",
	"Coldrock",
	"Lordale",
	"Westflower",
	"Deeplight",
	"Goldhollow",
	"Redfay",
	"Shadowcrest",
	"Swynland",
	"Mallowlyn",
	"Shadowshore",
	"Crystalwilde",
	"Mallowrose",
	"Eastspring",
	"Rosenesse",
	"Iceness",
	"Northbeach",
	"Dracwynne",
	"Merrimead",
	"Southhollow",
	"Esterway",
	"Bluemill",
	"Marbleport",
	"Elffield",
	"Meadowcoast"]

export default SettlementGenerator
